server:
  port: 8081
  servlet:
    context-path: /vehiclesys

spring:
    datasource:
        name: test
        url: jdbc:mysql://193.112.105.43:3306/carmonitor?serverTimezone=Shanghai&useSSL=false
        username: root
        password: rycuj9_Jian
        # 使用druid数据源
        #type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    resources:
      static-locations: classpath:/META-INF/resources/